version: '2'

services:
  hello:
    image: buoyantio/helloworld
    ports:
    - "7777:7777"
    command: -target linkerd:4140 -protocol grpc
  world:
    image: buoyantio/helloworld
    ports:
    - "7778:7778"
    command: -addr :7778 -text world -protocol grpc

  # linkerd
  linkerd:
    image: buoyantio/linkerd
    ports:
    - "9990:9990"
    - "50053:50053"
    - "4141:4141"
    - "4140:4140"
    # we must mount the config file and the disco directory
    volumes:
    - ./linkerd.yaml:/io.buoyant/linkerd.yaml:rw
    command: >
      /io.buoyant/linkerd.yaml