defaultEntryPoints = ["grpc-in"]
debug = true

# For secure connection on backend.local
RootCAs = [ "./backend.cert" ]

[entryPoints]
  [entryPoints.grpc-in]
  address = ":4140"


[web]
  address = ":8080"

[file]

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    # Access on backend with HTTPS
    url = "http://hello:7777"
  [backends.backend2]
    [backends.backend2.servers.server2]
    # Access on backend with HTTPS
    url = "http://world:7778"


[frontends]
  [frontends.frontend1]
  backend = "backend1"
    [frontends.frontend1.routes.test_1]
    rule = "Path:/toto"
  [frontends.frontend2]
  backend = "backend2"
    [frontends.frontend2.routes.test_2]
    rule = "Path:/"